name: publish-stable:aws

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  aws-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on AWS
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12
            registry-url: https://registry.npmjs.org/
      - run: yarn install --ignore-scripts
      - run: yarn release
      - run: yarn release:win
        env:
            IS_CI: "true"
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Get deploy version
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Trigger slack notification bot [Success]
        if: success()
        run: 'curl --data "status=success&user=${{ github.actor }}&platform=brew&version=${{ steps.branch_name.outputs.SOURCE_TAG }}" --header "token: super-secret-token" https://master--vtex.myvtex.com/_v/public/toolbelt-notification/status'
      - name: Trigger slack notification bot [Fail]
        if: failure()
        run: 'curl --data "status=failed&user=${{ github.actor }}&platform=brew&version=${{ steps.branch_name.outputs.SOURCE_TAG }}" --header "token: super-secret-token" https://master--vtex.myvtex.com/_v/public/toolbelt-notification/status'
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: vtex/homebrew-vtex
          event-type: bump-brew